
export const NETWORK_ERROR = 'NETWORK_ERROR';
export const INTERNAL_ERROR = 'INTERNAL_ERROR';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const INCORRECT_PASSWORD = 'INCORRECT_PASSWORD';
export const INCORRECT_EMAIL = 'INCORRECT_EMAIL';
export const INCORRECT_USERNAME = 'INCORRECT_USERNAME';

export const LOGOUT = 'LOGOUT';

export const PLACE_BID_REQUEST = 'PLACE_BID_REQUEST';
export const PLACE_BID_SUCCESS = 'PLACE_BID_SUCCESS';
export const PLACE_BID_FAILURE = 'PLACE_BID_FAILURE';

export const CREATE_AUCTION_REQUEST = 'CREATE_AUCTION_REQUEST';
export const CREATE_AUCTION_SUCCESS = 'CREATE_AUCTION_SUCCESS';
export const CREATE_AUCTION_FAILURE = 'CREATE_AUCTION_FAILURE';


export const EDIT_AUCTION_REQUEST = 'EDIT_AUCTION_REQUEST';
export const EDIT_AUCTION_SUCCESS = 'EDIT_AUCTION_SUCCESS';
export const EDIT_AUCTION_FAILURE = 'EDIT_AUCTION_FAILURE';


export const EDIT_USER_PROFILE_REQUEST = 'EDIT_USER_PROFILE_REQUEST';
export const EDIT_USER_PROFILE_SUCCESS = 'EDIT_USER_PROFILE_SUCCESS';
export const EDIT_USER_PROFILE_FAILURE = 'EDIT_USER_PROFILE_FAILURE';


export const EDIT_AUCTIONEER_REQUEST = 'EDIT_AUCTIONEER_REQUEST';
export const EDIT_AUCTIONEER_SUCCESS = 'EDIT_AUCTIONEER_SUCCESS';
export const EDIT_AUCTIONEER_FAILURE = 'EDIT_AUCTIONEER_FAILURE';


export const FETCH_AUCTIONS_REQUEST = 'FETCH_AUCTIONS_REQUEST';
export const FETCH_AUCTIONS_SUCCESS = 'FETCH_AUCTIONS_SUCCESS';
export const FETCH_AUCTIONS_FAILURE = 'FETCH_AUCTIONS_FAILURE';


// fetch Auctioneers
export const FETCH_AUCTIONEERS_REQUEST = 'FETCH_AUCTIONEERS_REQUEST';
export const FETCH_AUCTIONEERS_SUCCESS = 'FETCH_AUCTIONEERS_SUCCESS';
export const FETCH_AUCTIONEERS_FAILURE = 'FETCH_AUCTIONEERS_FAILURE';

// fetch auctioneer
export const FETCH_AUCTIONEER_REQUEST = 'FETCH_AUCTIONEER_REQUEST';
export const FETCH_AUCTIONEER_SUCCESS = 'FETCH_AUCTIONEER_SUCCESS';
export const FETCH_AUCTIONEER_FAILURE = 'FETCH_AUCTIONEER_FAILURE';


export const CREATE_AUCTIONEER_REQUEST = 'CREATE_AUCTIONEER_REQUEST';
export const CREATE_AUCTIONEER_SUCCESS = 'CREATE_AUCTIONEER_SUCCESS';
export const CREATE_AUCTIONEER_FAILURE = 'CREATE_AUCTIONEER_FAILURE';

export const DELETE_AUCTIONEER_FAILURE = 'DELETE_AUCTIONEER_FAILURE';
export const DELETE_AUCTIONEER_SUCCESS = 'DELETE_AUCTIONEER_SUCCESS';
export const DELETE_AUCTIONEER_REQUEST = 'DELETE_AUCTIONEER_REQUEST';



export const DELETE_AUCTION_REQUEST = 'DELETE_AUCTION_REQUEST';