
export const NETWORK_ERROR = 'NETWORK_ERROR';
export const INTERNAL_ERROR = 'INTERNAL_ERROR';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const INCORRECT_PASSWORD = 'INCORRECT_PASSWORD';
export const INCORRECT_EMAIL = 'INCORRECT_EMAIL';
export const INCORRECT_USERNAME = 'INCORRECT_USERNAME';

export const LOGOUT = 'LOGOUT';

export const PLACE_BID_REQUEST = 'PLACE_BID_REQUEST';
export const PLACE_BID_SUCCESS = 'PLACE_BID_SUCCESS';
export const PLACE_BID_FAILURE = 'PLACE_BID_FAILURE';

export const FETCH_BIDS_REQUEST = 'FETCH_BIDS_REQUEST';
export const FETCH_BIDS_SUCCESS = 'FETCH_BIDS_SUCCESS';
export const FETCH_BIDS_FAILURE = 'FETCH_BIDS_FAILURE';

export const UPDATE_BID_REQUEST = 'UPDATE_BID_REQUEST';
export const UPDATE_BID_SUCCESS = 'UPDATE_BID_SUCCESS';
export const UPDATE_BID_FAILURE = 'UPDATE_BID_FAILURE';

export const DELETE_BID_REQUEST = 'DELETE_BID_REQUEST';
export const DELETE_BID_SUCCESS = 'DELETE_BID_SUCCESS';
export const DELETE_BID_FAILURE = 'DELETE_BID_FAILURE';

export const CREATE_AUCTION_REQUEST = 'CREATE_AUCTION_REQUEST';
export const CREATE_AUCTION_SUCCESS = 'CREATE_AUCTION_SUCCESS';
export const CREATE_AUCTION_FAILURE = 'CREATE_AUCTION_FAILURE';

export const FETCH_AUCTION_REQUEST = 'FETCH_AUCTION_REQUEST';
export const FETCH_AUCTION_SUCCESS = 'FETCH_AUCTION_SUCCESS';
export const FETCH_AUCTION_FAILURE = 'FETCH_AUCTION_FAILURE';

export const DELETE_AUCTION_SUCCESS = 'DELETE_AUCTION_SUCCESS';
export const DELETE_AUCTION_FAILURE = 'DELETE_AUCTION_FAILURE';

export const EDIT_AUCTION_REQUEST = 'EDIT_AUCTION_REQUEST';
export const EDIT_AUCTION_SUCCESS = 'EDIT_AUCTION_SUCCESS';
export const EDIT_AUCTION_FAILURE = 'EDIT_AUCTION_FAILURE';

export const CLOSE_BID_REQUEST = 'CLOSE_BID_REQUEST';
export const CLOSE_BID_SUCCESS = 'CLOSE_BID_SUCCESS';
export const CLOSE_BID_FAILURE = 'CLOSE_BID_FAILURE';

export const EDIT_USER_PROFILE_REQUEST = 'EDIT_USER_PROFILE_REQUEST';
export const EDIT_USER_PROFILE_SUCCESS = 'EDIT_USER_PROFILE_SUCCESS';
export const EDIT_USER_PROFILE_FAILURE = 'EDIT_USER_PROFILE_FAILURE';

export const EDIT_AUCTIONEER_REQUEST = 'EDIT_AUCTIONEER_REQUEST';
export const EDIT_AUCTIONEER_SUCCESS = 'EDIT_AUCTIONEER_SUCCESS';
export const EDIT_AUCTIONEER_FAILURE = 'EDIT_AUCTIONEER_FAILURE';

export const FETCH_AUCTIONS_REQUEST = 'FETCH_AUCTIONS_REQUEST';
export const FETCH_AUCTIONS_SUCCESS = 'FETCH_AUCTIONS_SUCCESS';
export const FETCH_AUCTIONS_FAILURE = 'FETCH_AUCTIONS_FAILURE';
// fetch Auctioneers
export const FETCH_AUCTIONEERS_REQUEST = 'FETCH_AUCTIONEERS_REQUEST';
export const FETCH_AUCTIONEERS_SUCCESS = 'FETCH_AUCTIONEERS_SUCCESS';
export const FETCH_AUCTIONEERS_FAILURE = 'FETCH_AUCTIONEERS_FAILURE';
// fetch auctioneer
export const FETCH_AUCTIONEER_REQUEST = 'FETCH_AUCTIONEER_REQUEST';
export const FETCH_AUCTIONEER_SUCCESS = 'FETCH_AUCTIONEER_SUCCESS';
export const FETCH_AUCTIONEER_FAILURE = 'FETCH_AUCTIONEER_FAILURE';

export const CREATE_AUCTIONEER_REQUEST = 'CREATE_AUCTIONEER_REQUEST';
export const CREATE_AUCTIONEER_SUCCESS = 'CREATE_AUCTIONEER_SUCCESS';
export const CREATE_AUCTIONEER_FAILURE = 'CREATE_AUCTIONEER_FAILURE';

export const DELETE_AUCTIONEER_FAILURE = 'DELETE_AUCTIONEER_FAILURE';
export const DELETE_AUCTIONEER_SUCCESS = 'DELETE_AUCTIONEER_SUCCESS';
export const DELETE_AUCTIONEER_REQUEST = 'DELETE_AUCTIONEER_REQUEST';

export const DELETE_AUCTION_REQUEST = 'DELETE_AUCTION_REQUEST';

export const SET_IS_REGISTERED_NOW = 'SET_IS_REGISTERED_NOW';


export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAILURE = 'UPDATE_USER_PROFILE_FAILURE';

export const DELETE_USER_ACCOUNT_REQUEST = 'DELETE_USER_ACCOUNT_REQUEST';
export const DELETE_USER_ACCOUNT_SUCCESS = 'DELETE_USER_ACCOUNT_SUCCESS';
export const DELETE_USER_ACCOUNT_FAILURE = 'DELETE_USER_ACCOUNT_FAILURE';

export const FETCH_USER_PROFILE_FAILURE = 'FETCH_USER_PROFILE_FAILURE';
export const FETCH_USER_PROFILE_REQUEST = 'FETCH_USER_PROFILE_REQUEST';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';


export const CREATE_USER_PROFILE_FAILURE = 'CREATE_USER_PROFILE_FAILURE';
export const CREATE_USER_PROFILE_REQUEST = 'CREATE_USER_PROFILE_REQUEST';
export const CREATE_USER_PROFILE_SUCCESS = 'CREATE_USER_PROFILE_SUCCESS';

